name: Run tests and linting on pull requests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # make sure we don't pick up our repo's .npmrc
      - name: Un-configure GitHub Packages
        run: rm -f .npmrc

      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-install-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}

      - run: yarn install --prefers-offline
        if: ${{ steps.yarn-cache.outputs.cache-hit == 'true' }}

      - run: yarn run test
      - run: yarn run lint
